account/urls.py
from django.urls import path
from .views import register,update,profile

app_name = 'account'

urlpatterns = [
    path('register/', register, name = 'register' ),
    path('update/', update, name = 'update'),
    path('profile', profile, name = 'profile')
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls', namespace='core')),
    path('account/',include('account.urls', namespace='account')),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html') , name ='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='account/logout.html') , name ='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import home, post_detail_view,CreatePost

app_name = 'core'

urlpatterns = [
    path('', home , name ='home'),
    path('detail/<int:id>', post_detail_view, name = 'detail'),
    path('create-post/', CreatePost.as_view(), name = 'create-post')
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='pictures',default='default.png')


    def __str__(self):
        return self.user.username

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()


class Category(models.Model):

    title = models.CharField(max_length=25)

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=25)
    content = models.TextField()
    is_complete = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add = True)
    category =  models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('core:detail', kwargs = {'id':self.id})

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

User = get_user_model()


class RegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username','password1','password2','email'
        ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']



class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['photo']

account/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,UserUpdateForm,ProfileUpdateForm
from django.contrib import messages

# Create your views here.


def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST or None)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Hi {username} your account created successfull, you can now log')
            return redirect('login')


    else:
        form = RegisterForm()

    
    return render(request, 'account/register.html', {'form':form})


def update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, request.FILES, instance = request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            messages.success(request, f'profile updated successfully!')
            return redirect('account:profile')

    else:

        u_form = UserUpdateForm(instance = request.user, )
        p_form = ProfileUpdateForm( instance = request.user.profile )



    return render(request, 'account/update.html',{
        'u_form':u_form,
        'p_form':p_form
    })




def profile(request):
    return render(request,'account/profile.html')

core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post
from django.views import generic
# Create your views here.


def home(request):
    posts = Post.objects.order_by('date')[:]
    context = {
        'posts':posts
    }
    return render(request, 'core/home.html', context)



def post_detail_view(request,id):
    post = get_object_or_404(Post, id=id)

    context = {
        'post':post
    }

    return render(request, 'core/post_detail.html',context)



class   CreatePost(generic.CreateView):
    
    model = Post
    template_name = 'core/create_post.html'
    fields = [
        'title','content','category','is_complete'
    ]


    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

core/templates/core/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'core/nav.html' %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

core/templates/core/create_post.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
           <div class="form-control">
            <h2>Create a new Post</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary mt-2">Save</button>
            </form>
           </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% block content  %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="home">
                {% for p in posts %}
                <img  width="75px" margin-left="20px" class="rounded-circle" src="{{p.author.profile.photo.url}}" alt="">
                <div class="content">
                   <a href="{{p.get_absolute_url}}"> <h2>{{p.title}}</h2></a>
                    <small>By {{p.author.username}} on {{p.date|timesince}}</small>
                    <p>{{p.content}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:register' %}">Sign Up</a>
            </li>
            
          </ul>
        
      </div>
    </div>
  </nav>

core/templates/core/post_detail.html
{% extends 'core/base.html' %}
{% block content  %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="home">
                
                <img  width="75px" margin-left="20px" class="rounded-circle" src="{{p.author.profile.photo.url}}" alt="">
                <div class="content">
                    <h2>{{post.title}}</h2>
                    <small>By {{post.author.username}} on {{post.date|timesince}}</small>
                    <p>{{post.content}}</p>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}